// PowerPC CPU Context Definition for XenonRecomp
// Based on rexdex/recompiler approach but adapted to XenonRecomp's style

#pragma once

#include <cstdint>
#include <array>

// PPC Register types
using TReg = uint64_t;       // 64-bit general purpose register
using TFReg = double;        // Floating point register
using VReg = __m128;         // Vector register (using SSE/AVX intrinsics)

// PowerPC Condition Register bit fields
struct ControlReg 
{
    uint8_t lt : 1;  // Less Than (LT)
    uint8_t gt : 1;  // Greater Than (GT) 
    uint8_t eq : 1;  // Equal (EQ)
    uint8_t so : 1;  // Summary Overflow (SO)
    uint8_t pad : 4; // Padding to ensure 8-bit size
};

// XER register structure (Fixed-Point Exception Register)
struct XerReg
{
    uint32_t so : 1;   // Summary Overflow
    uint32_t ov : 1;   // Overflow 
    uint32_t ca : 1;   // Carry
    uint32_t pad : 29; // Padding
};

// Memory reservation for load/store conditional
struct Reservation
{
    uint64_t address;
    uint64_t size;
    uint8_t data[16];
};

// Full PowerPC CPU state
struct PPCContext
{
    // Special registers
    TReg        LR;        // Link Register
    TReg        CTR;       // Count Register
    TReg        MSR;       // Machine State Register
    XerReg      XER;       // Fixed-Point Exception Register
    ControlReg  CR[8];     // Condition Registers (8 groups of 4 bits)
    uint32_t    FPSCR;     // Floating-Point Status and Control Register

    // General purpose registers
    TReg        R[32];     // General Purpose Registers (R0-R31)

    // Floating point registers
    TFReg       FR[32];    // Floating Point Registers (FR0-FR31)

    // Vector registers (VMX)
    VReg        VR[128];   // Vector Registers (VR0-VR127)

    // Memory reservation
    Reservation* RES;
    
    // Floating-point environment state
    bool        denorm_flush_to_zero;
};

// Helper namespace for instruction implementation
namespace ppc {
    // Mask generation utilities
    inline uint64_t RotateMask(uint32_t mb, uint32_t me) {
        mb &= 0x3F;
        me &= 0x3F;
        uint64_t mask = (UINT64_MAX >> mb) ^ ((me >= 63) ? 0 : UINT64_MAX >> (me + 1));
        return mb <= me ? mask : ~mask;
    }

    // Bit manipulation helpers
    template<int N>
    inline uint64_t RotateLeft(uint64_t value) {
        if constexpr (N == 0) return value;
        return (value << N) | (value >> (64 - N));
    }

    // Sign extension helpers
    inline int64_t SignExtend32(int32_t value) {
        return static_cast<int64_t>(value);
    }

    inline int64_t SignExtend16(int16_t value) {
        return static_cast<int64_t>(value);
    }
}

// Generated by XenonAnalyse
// ---- ABSOLUTE JUMPTABLE ----
// ---- COMPUTED JUMPTABLE ----
// ---- OFFSETED JUMPTABLE ----
